server:
  port: 8447




spring:
  jpa.hibernate.ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/wpng?useSSL=false
    username: wpnguser
    password: secret


logging:
  level:
    root: INFO
    com.wiley.wpng.ref.api: DEBUG
    org.jose4j.jwt: TRACE

