server:
  port: 8444
  ssl:
    key-password: changeit
    key-store: classpath:thekeystore
    key-store-provider: SUN
    key-store-type: JKS
    key-alias: cas


logging:
  level:
    root: INFO
    com.wiley.wpng.ref.api.auth: DEBUG


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wpng?useSSL=false
    username: wpnguser
    password: secret



