# Default OpenID Connect Issuers
# This should be overriden in the project using the security library
oidc:
  oidcIssuers:
    http://localhost:8080/cas/oidc: https://localhost:8443/cas/oidc/jwks
    https://parkerneff.auth0.com/: https://parkerneff.auth0.com/.well-known/jwks.json
    http://reflti.wiley.com: https://localhost:8447/oidc/jwks
